# Generated by Django 6.0.4 on 2026-04-16 13:24

import extra_settings.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_settings', '0008_auto_20221024_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value_file',
            field=models.FileField(blank=True, storage=extra_settings.fields.get_file_storage, upload_to=extra_settings.fields.upload_to_files, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_image',
            field=models.FileField(blank=True, storage=extra_settings.fields.get_image_storage, upload_to=extra_settings.fields.upload_to_images, verbose_name='Value'),
        ),
    ]
