# Generated by Django 6.0.3 on 2026-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extra_settings", "0008_auto_20221024_0717"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="value_password",
            field=models.TextField(blank=True, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="setting",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("bool", "bool"),
                    ("date", "date"),
                    ("datetime", "datetime"),
                    ("decimal", "decimal"),
                    ("duration", "duration"),
                    ("email", "email"),
                    ("file", "file"),
                    ("float", "float"),
                    ("image", "image"),
                    ("int", "int"),
                    ("json", "json"),
                    ("string", "string"),
                    ("password", "password"),
                    ("text", "text"),
                    ("time", "time"),
                    ("url", "url"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
