# Generated by Django 5.1.6 on 2025-02-07 14:30

import extra_settings.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("extra_settings", "0001_initial"),
        ("extra_settings", "0002_auto_20200826_1714"),
        ("extra_settings", "0003_modified_upload_to"),
        ("extra_settings", "0004_setting_description"),
        ("extra_settings", "0005_setting_value_json_alter_setting_value_type"),
        ("extra_settings", "0006_setting_validator"),
        ("extra_settings", "0007_alter_settings_validator"),
        ("extra_settings", "0008_auto_20221024_0717"),
        ("extra_settings", "0009_alter_value_json"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="(e.g. SETTING_NAME)",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("bool", "bool"),
                            ("date", "date"),
                            ("datetime", "datetime"),
                            ("decimal", "decimal"),
                            ("duration", "duration"),
                            ("email", "email"),
                            ("file", "file"),
                            ("float", "float"),
                            ("image", "image"),
                            ("int", "int"),
                            ("json", "json"),
                            ("string", "string"),
                            ("text", "text"),
                            ("time", "time"),
                            ("url", "url"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "value_bool",
                    models.BooleanField(default=False, verbose_name="Value"),
                ),
                (
                    "value_date",
                    models.DateField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "value_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        default=Decimal("0.0"),
                        max_digits=19,
                        verbose_name="Value",
                    ),
                ),
                (
                    "value_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Value"),
                ),
                (
                    "value_file",
                    models.FileField(
                        blank=True,
                        upload_to=extra_settings.fields.upload_to_files,
                        verbose_name="Value",
                    ),
                ),
                (
                    "value_float",
                    models.FloatField(blank=True, default=0.0, verbose_name="Value"),
                ),
                (
                    "value_image",
                    models.FileField(
                        blank=True,
                        upload_to=extra_settings.fields.upload_to_images,
                        verbose_name="Value",
                    ),
                ),
                (
                    "value_int",
                    models.IntegerField(blank=True, default=0, verbose_name="Value"),
                ),
                (
                    "value_string",
                    models.CharField(blank=True, max_length=255, verbose_name="Value"),
                ),
                ("value_text", models.TextField(blank=True, verbose_name="Value")),
                (
                    "value_time",
                    models.TimeField(blank=True, null=True, verbose_name="Value"),
                ),
                ("value_url", models.URLField(blank=True, verbose_name="Value")),
                (
                    "value_duration",
                    models.DurationField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "value_json",
                    models.JSONField(blank=True, default=dict, verbose_name="Value"),
                ),
                (
                    "validator",
                    models.CharField(
                        blank=True,
                        help_text="Full python path to a validator function, "
                        + "eg. 'myapp.mymodule.my_validator'",
                        max_length=255,
                        null=True,
                        verbose_name="Validator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "ordering": ["name"],
            },
        ),
    ]
